field.storage_settings.blog_publish:
  type: mapping
  label: 'Datetime settings'
  mapping:
    datetime_type:
      type: string
      label: 'Date type'
field.formatter.settings.blog_publish_generic_formatter:
  type: mapping
  label: 'Generic formatter'
  mapping:
    date_format:
      type: string
      label: 'Generic formatter'
    text_pattern:
      type: string
      label: 'Text replace pattern'
